trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: 'terraform'
  serviceConnection: 'azure-devops-sc'

stages:

# Validation Stage
- stage: Validate
  displayName: Terraform Validation

  jobs:
    - job: Validation

      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - task: AzureCLI@2
          displayName: Azure Login
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az account show

        - script: |
            terraform init -backend=false
          workingDirectory: $(workingDirectory)
          displayName: Terraform Init

        - script: |
            terraform fmt -check -recursive
          workingDirectory: $(workingDirectory)
          displayName: Terraform FMT

        - script: |
            terraform validate
          workingDirectory: $(workingDirectory)
          displayName: Terraform Validate

# Security Scanning Stage
- stage: SecurityScanning
  displayName: Security Scanning
  dependsOn: Validate

  jobs:
    - job: TerraformSecurityScan

      steps:

        - script: |
            tflint
          workingDirectory: $(workingDirectory)
          displayName: TFLint

        - script: |
            tfsec .
          workingDirectory: $(workingDirectory)
          displayName: TFSec

        - script: |
            checkov -d .
          workingDirectory: $(workingDirectory)
          displayName: Checkov

        - script: |
            gitleaks detect --source .
          workingDirectory: $(workingDirectory)
          displayName: Gitleaks

        - script: |
            infracost breakdown --path .
          workingDirectory: $(workingDirectory)
          displayName: Infracost

# DEV PLAN
- stage: DevPlan
  dependsOn: SecurityScanning
  jobs:
    - job: Plan
      steps:
        - script: |
            terraform plan \
              -var-file=environments/dev.tfvars \
              -out=dev.tfplan


# DEV APPLY
- stage: DevApply
  dependsOn: DevPlan
  jobs:
    - deployment: DeployDev
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: terraform apply -auto-approve dev.tfplan


# DEV VALIDATION
- stage: DevValidation
  dependsOn: DevApply
  jobs:
    - job: Validation
      steps:
        - script: terraform output

# QA PLAN
- stage: QaPlan
  dependsOn: DevValidation
  jobs:
    - job: Plan
      steps:
        - script: |
            terraform plan \
              -var-file=environments/qa.tfvars \
              -out=qa.tfplan

# QA APPLY
- stage: QaApply
  dependsOn: QaPlan
  jobs:
    - deployment: DeployQA
      environment: qa
      strategy:
        runOnce:
          deploy:
            steps:
              - script: terraform apply -auto-approve qa.tfplan


# QA VALIDATION
- stage: QaValidation
  dependsOn: QaApply
  jobs:
    - job: Validation
      steps:
        - script: terraform output


# PROD PLAN
- stage: ProdPlan
  dependsOn: QaValidation
  jobs:
    - job: Plan
      steps:
        - script: |
            terraform plan \
              -var-file=environments/prod.tfvars \
              -out=prod.tfplan


# PROD APPLY
- stage: ProdApply
  dependsOn: ProdPlan
  jobs:
    - deployment: DeployProd
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
              - script: terraform apply prod.tfplan


# MONITORING
- stage: Monitoring
  dependsOn: ProdApply
  jobs:
    - job: Monitoring
      steps:
        - script: echo "Azure Monitor Checks"


# DRIFT DETECTION
- stage: DriftDetection
  dependsOn: Monitoring
  jobs:
    - job: Drift
      steps:
        - script: terraform plan -refresh-only