trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: 'environment'

stages:

# Validation Stage
- stage: Validate
  displayName: Terraform Validation

  jobs:
    - job: Validation

      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - script: |
            terraform init -backend=false
          workingDirectory: $(workingDirectory)
          displayName: Terraform Init

        - script: |
            terraform fmt -check -recursive
          workingDirectory: $(workingDirectory)
          displayName: Terraform FMT

        - script: |
            terraform validate
          workingDirectory: $(workingDirectory)
          displayName: Terraform Validate

# Security Scanning Stage
- stage: SecurityScanning
  displayName: Security Scanning
  dependsOn: Validate

  jobs:
    - job: TerraformSecurityScan

      steps:

        - script: |
            tflint
          workingDirectory: $(workingDirectory)
          displayName: TFLint

        - script: |
            tfsec .
          workingDirectory: $(workingDirectory)
          displayName: TFSec

        - script: |
            checkov -d .
          workingDirectory: $(workingDirectory)
          displayName: Checkov

        - script: |
            gitleaks detect --source .
          workingDirectory: $(workingDirectory)
          displayName: Gitleaks

        - script: |
            infracost breakdown --path .
          workingDirectory: $(workingDirectory)
          displayName: Infracost