Name: PR Pipeline

trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest


stages:
# Validation Stage
- stage: Validate
  displayName: Terraform Validation
  jobs:
    - job: Validation
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - script: |
            terraform fmt -check -recursive
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: Terraform FMT

        - script: |
            terraform init -backend=false
            terraform validate
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: Terraform Validate

# Security Scanning Stage
- stage: SecurityScanning
  displayName: Security Scanning
  dependsOn: Validate
  jobs:
    - job: TerraformSecurityScan

      steps:

        # - script: |
        #     tflint
        #   workingDirectory: $(workdir)
        #   displayName: TFLint

        - script: |
            tfsec .
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: TFSec

        - script: |
            checkov -d .
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: Checkov

        - script: |
            gitleaks detect --source .
          workingDirectory: $(System.DefaultWorkingDirectory)
          displayName: Gitleaks

        # - script: |
        #     infracost breakdown --path .
        #   workingDirectory: $(workdir)
        #   displayName: Infracost