parameters:
  environment: ""

stages:

- stage: Approval

  dependsOn: Plan

  condition: |
    or(
      eq('${{ parameters.environment }}','quality'),
      eq('${{ parameters.environment }}','production')
    )

  jobs:

  - job: Approval

    pool: server

    steps:

    - task: ManualValidation@0
      timeoutInMinutes: 1440

      inputs:
        notifyUsers: |
          amitkkc01@gmail.com

        instructions: |
          Review Terraform Plan and approve.

        onTimeout: reject
